### ISSUE TITLE
Docker compose fails on tig-data in "tig-stack"

### ISSUE THREAD

**Issue by Erikmmkarlsson** [iot-lnu/applied-iot-20#3]
While in TIG-stack (I only copied that folder, maybe that's the problem?), I get this following error when running docker-compose (on both windows and Linux Ubuntu):

![bild](https://user-images.githubusercontent.com/56456582/123555203-87dd1500-d784-11eb-9926-0502177887ca.png)

The problem is that tig-data doesn't have any clear mounting "spot".

I tried previous versions where the volumes were defined as: `- ./data:/var/lib/influxdb` and `- ./data/grafana:/var/lib/grafana` and it worked fine.

**Comment by frahlg** [comment]
In the docker-compose it should create a volume called `tig-data`. The only local mount needed should be the telegraf config file. Are you starting with `docker-compose up` ? It shouldn't need any arguments.

**Comment by frahlg** [comment]
I have updated the `docker-compose` file with absolute paths. It seems that it might have been a change in how Grafana handled the volumes in Docker with newer versions. Everything should work as intended now.
